apiVersion: batch/v1
kind: CronJob
metadata:
  name: sage-dict-sync-cron-job
  namespace: dmp
spec:
  schedule: "0 5 * * *"
  timeZone: "Asia/Shanghai"
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: Never
          containers:
            - name: main
              image: pre-registry-docker:5000/sage-dict-sync:0.1.1
              imagePullPolicy: IfNotPresent
              command: ["/opt/sage-dict-sync/bin/sage-dict-sync", "-c"]
              args: ["/opt/sage-dict-sync/conf/config.toml"]
              volumeMounts:
                - name: config
                  mountPath: "/opt/sage-dict-sync/conf"
                  readOnly: true
          volumes:
            - name: config
              configMap:
                name: sage-dict-sync-tasks
                items:
                  - key: haima_service_code_desc.toml
                    path: config.toml
