fields = ["data", "name", "description"]
relation = ["data"]

[from]
db = "mysql://bigdata:bigdata@10.201.10.252:3306/db_company_mgt"
query = "SELECT  bid as data, bid_name  as  name, IFNULL(comments, '')  as description from t_oid_bid_info"

[dist]
db = "mysql://bigdata:bigdata@10.201.10.252:3306/dmp"
query = "select data,name,description from dmp_ai_data_dict where field = 'bid'"
insert = "insert into dmp_ai_data_dict(field, data, name, description) value('bid', :data, :name, :description)"
update = "update dmp_ai_data_dict set name=:name,description=:description where field = 'bid' and data = :data"
delete = "delete from dmp_ai_data_dict where name=:name and field = 'bid'"
