fields = ["data", "name", "description"]
relation = ["data"]

[from]
db = "mysql://bigdata:bigdata@10.201.10.252:3306/db_company_mgt"
query = "SELECT  bid as data, bid_name  as  name, CONCAT('bandwidth: ', bandwidth, ', pcu: ',pcu, ' (1有效,0无效)')  as description from t_fictitious_bid"

[dist]
db = "mysql://bigdata:bigdata@10.201.10.252:3306/dmp"
query = "select data,name,description from dmp_ai_data_dict where field = 'vid'"
insert = "insert into dmp_ai_data_dict(field, data, name, description) value('vid', :data, :name, :description)"
update = "update dmp_ai_data_dict set name=:name,description=:description where field = 'vid' and data = :data"
delete = "delete from dmp_ai_data_dict where name=:name and field = 'vid'"
